
/*
CREATE TABLE `workers_document` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `worker_key` integer NOT NULL,
  `document_link` varchar(255) DEFAULT NULL,
  `type_of_douments` varchar(255) DEFAULT NULL,
  `document_id` varchar(50) DEFAULT NULL,
  `place_of_issue` text,
  `document_issued_date` varchar(20) DEFAULT NULL,
  `document_expiry_date` varchar(20) DEFAULT NULL,
  `issuing_country` varchar(255) DEFAULT NULL,
  `document_status` varchar(255) DEFAULT NULL,
  `status_of_current_document` varchar(255) DEFAULT NULL
);



CREATE TABLE `users`(
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL UNIQUE,
  `password` varchar(255) NOT NULL,
  `device_status_online` varchar(255) NULL,
  `user_status` varchar(255) NULL,
  `created_at` varchar(255) NULL,
  `created_time` varchar(255) NULL
);



CREATE TABLE `profile` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `aps_agency_pekerjaan` varchar(255) NULL,
  `aps_license_category` varchar(255) NULL,
  `aps_postcode` varchar(255) NULL,
  `aps_office_telephone_no` varchar(20) NULL,
  `aps_new_ssm_number` varchar(255) NULL,
  `aps_address1` text NULL,
  `aps_city` varchar(255) NULL,
  `aps_mobile_number` varchar(20) NULL,
  `aps_old_SSM_number` varchar(20) NULL,
  `aps_address2` text NULL,
  `aps_state` varchar(255) NULL,
  `aps_email` varchar(100) NOT NULL UNIQUE,
  `aps_license_no` varchar(20) NULL,
  `aps_address3` text NULL,
  `aps_license_exp_date` varchar(20) NULL,
  `aps_contact_person` varchar(255) NULL,
  `employer_company_name` varchar(255) NULL,
  `employer_new_ssm_number` varchar(255) NULL,
  `employer_old_ssm_number` varchar(20) NULL,
  `employer_address1` text NULL,
  `employer_address2` text NULL,
  `employer_address3` text NULL,
  `employer_postcode` varchar(20) NULL,
  `employer_city` varchar(255) NULL,
  `employer_state` varchar(255) NULL,
  `employer_office_telephone_no` varchar(20) NULL,
  `employer_mobile_no` varchar(20) NULL,
  `employer_fax_number` varchar(20) NULL,
  `employer_year_of_commence` varchar(20) NULL,
  `employer_sector` varchar(255) NULL,
  `employer_name_of_person_in_charge` text NULL,
  `employer_designation` varchar(255) NULL,
  `employer_pic_mobile_number` varchar(20) NULL,
  `branch_employment_location_name` varchar(255) NULL,
  `branch_address1` text NULL,
  `branch_address2` text NULL,
  `branch_address3` text NULL,
  `branch_postcode` varchar(20) NULL,
  `branch_state` varchar(255) NULL,
  `branch_city` varchar(255) NULL,
  `branch_office_telephone_number` varchar(20) NULL,
  `branch_office_mobile_number` varchar(20) NULL,
  `branch_email` varchar(100) NULL,
  `branch_name_of_person_in_charge` varchar(255) NULL,
  `branch_designation` varchar(255) NULL,
  `branch_pic_mobile_number` varchar(20) NULL
);



CREATE TABLE `half_form` (
  `id` integer NOT NULL primary key AUTOINCREMENT,
  `worker_key` integer NOT NULL,
  `form_created_by` varchar(255) NOT NULL,
  `form_created_date` varchar(255) NOT NULL,
  `form_worker_reg_no` varchar(255) NOT NULL,
  `no_family_mem` varchar(255) NOT NULL,
  `worker_detail_worker_legal_status` varchar(255) NOT NULL,
  `worker_detail_name_of_worker` varchar(255) NOT NULL,
  `worker_detail_family_name` varchar(255) NOT NULL,
  `worker_detail_gender` varchar(255) NOT NULL,
  `worker_detail_DOB` varchar(255) NOT NULL,
  `worker_detail_place_birth` varchar(255) NOT NULL,
  `worker_detail_citizenship` varchar(255) NOT NULL,
  `worker_detail_marital_status` varchar(255) NOT NULL,
  `worker_detail_poe` varchar(255) NOT NULL,
  `worker_detail_religion` varchar(255) NOT NULL,
  `worker_detail_race` varchar(255) NOT NULL,
  `worker_detail_contact_no` varchar(255) NOT NULL,
  `worker_detail_email` varchar(255) NOT NULL,
  `worker_detail_nok` varchar(255) NOT NULL,
  `worker_detail_relationship` varchar(255) NOT NULL,
  `worker_detail_nok_contact_no` varchar(255) NOT NULL,
  `worker_emp_dtl_job_sector` varchar(255) NOT NULL,
  `worker_emp_dtl_job_sub_sector` varchar(255) NOT NULL,
  `worker_emp_dtl_emp_sponsorship_status` varchar(255) NOT NULL,
  `worker_emp_dtl_address1` varchar(255) NOT NULL,
  `worker_emp_dtl_address2` varchar(255) NOT NULL,
  `worker_emp_dtl_address3` varchar(255) NOT NULL,
  `worker_emp_dtl_postcode` varchar(255) NOT NULL,
  `worker_emp_dtl_city` varchar(255) NOT NULL,
  `worker_emp_dtl_state` varchar(255) NOT NULL,
  `worker_doc_dtl_doc_id` varchar(255) NOT NULL,
  `worker_doc_dtl_type_of_doc` varchar(255) NOT NULL,
  `worker_doc_dtl_no_of_doc` varchar(255) NOT NULL,
  `worker_doc_dtl_images_path_email` varchar(255) NOT NULL,
  `worker_doc_dtl_place_of_issue` varchar(255) NOT NULL,
  `worker_doc_dtl_issue_date` varchar(255) NOT NULL,
  `worker_doc_dtl_expiry_date` varchar(255) NOT NULL,
  `worker_doc_dtl_country_doc_issued` varchar(255) NOT NULL,
  `worker_doc_dtl_doc_status` varchar(255) NOT NULL,
  `worker_doc_dtl_doc_current_status` varchar(255) NOT NULL,
  `worker_doc_dtl_doc_no` varchar(255) NOT NULL,
  `form_position` varchar(255) NOT NULL,
  `form_status` varchar(255) NOT NULL,
  `form_unique_key` varchar(255) NOT NULL UNIQUE
);


CREATE TABLE `workers_document` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `worker_key` integer NOT NULL,
  `document_link` varchar(255) DEFAULT NULL,
  `type_of_douments` varchar(255) DEFAULT NULL,
  `document_id` varchar(50) DEFAULT NULL,
  `place_of_issue` text,
  `document_issued_date` varchar(20) DEFAULT NULL,
  `document_expiry_date` varchar(20) DEFAULT NULL,
  `issuing_country` varchar(255) DEFAULT NULL,
  `document_status` varchar(255) DEFAULT NULL,
  `status_of_current_document` varchar(255) DEFAULT NULL,
  `form_unique_key` varchar(100) NOT NULL
);


CREATE TABLE `family_form` (
  `id` integer NOT NULL primary key autoincrement,
  `form_created_by` varchar(255) NOT NULL,
  `form_created_date` varchar(255) NULL,
  `form_unique_key` varchar(255) NOT NULL,
  `form_family_reg_no` varchar(255) NULL,
  `family_form_worker_name` varchar(255) NULL,
  `family_form_relationship` varchar(255) NULL,
  `family_form_name_of_family_member` varchar(255) NULL,
  `family_form_family_name` varchar(255) NULL,
  `family_form_is_famliy_togther` varchar(255) NULL,
  `family_form_family_form_poe` varchar(255) NULL,
  `family_form_citizenship` varchar(255) NULL,
  `family_form_religion` varchar(255) NULL,
  `family_form_marital_status` varchar(255) NULL,
  `family_form_gender` varchar(255) NULL,
  `family_form_address1` varchar(255) NULL,
  `family_form_address2` varchar(255) NULL,
  `family_form_address3` varchar(255) NULL,
  `family_form_postcode` varchar(255) NULL,
  `family_form_city` varchar(255) NULL,
  `family_form_state` varchar(255) NULL,
  `family_form_contact_no` varchar(255) NULL,
  `family_form_race` varchar(255) NULL,
  `family_form_place_of_birth` varchar(255) NULL,
  `family_form_emp_status` varchar(255) NULL,
  `family_form_emp_name` varchar(255) NULL,
  `family_form_emp_address` varchar(255) NULL,
  `family_form_doc_path_email` varchar(255) NULL,
  `family_form_doc_image_no` varchar(255) NULL,
  `worker_key` integer(11) NULL,
  `fmDoc1_type_of_documents` text,
  `fmDoc1_document_id` varchar(20) DEFAULT NULL,
  `fmDoc1_place_of_issue` varchar(20) DEFAULT NULL,
  `fmDoc1_document_issued_date` varchar(20) DEFAULT NULL,
  `fmDoc1_document_expiry_date` varchar(20) DEFAULT NULL,
  `fmDoc1_issuing_country` varchar(100) DEFAULT NULL,
  `fmDoc1_document_status` varchar(50) DEFAULT NULL,
  `fmDoc1_status_of_current_document` varchar(50) DEFAULT NULL,
  `fmDoc2_type_of_documents` text,
  `fmDoc2_document_id` varchar(20) DEFAULT NULL,
  `fmDoc2_place_of_issue` text,
  `fmDoc2_document_issued_date` varchar(20) DEFAULT NULL,
  `fmDoc2_document_expiry_date` varchar(20) DEFAULT NULL,
  `fmDoc2_issuing_country` varchar(150) DEFAULT NULL,
  `fmDoc2_document_status` varchar(50) DEFAULT NULL,
  `fmDoc2_status_of_current_document` varchar(50) DEFAULT NULL
);



CREATE TABLE `users`(
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL UNIQUE,
  `password` varchar(255) NOT NULL,
  `device_status_online` varchar(255) NULL,
  `user_status` varchar(255) NULL,
  `created_at` varchar(255) NULL,
  `created_time` varchar(255) NULL,
  `worker_registration_prefix` varchar(500) NOT NULL UNIQUE
);
*/

CREATE TABLE `sub_admin` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL UNIQUE,
  `password` varchar(20) NOT NULL,
  `status` varchar(255) NULL,
  `created_at` varchar(255) NULL,
  `created_time` varchar(255) NULL,
  `profile_path` text NULL,
  `last_signin` varchar(50) DEFAULT NULL,
  `last_signout` varchar(50) DEFAULT NULL,
  `session_time` varchar(50) DEFAULT NULL
);
