CREATE TABLE `family_form` (
  `id` integer NOT NULL primary key autoincrement,
  `form_created_by` varchar(255) NULL,
  `form_created_date` varchar(255) NULL,
  `form_unique_key` varchar(255) NULL,
  `form_family_reg_no` varchar(255) NULL,
  `family_form_worker_name` varchar(255) NULL,
  `family_form_relationship` varchar(255) NULL,
  `family_form_name_of_family_member` varchar(255) NULL,
  `family_form_family_name` varchar(255) NULL,
  `family_form_is_famliy_togther` varchar(255) NULL,
  `family_form_family_form_poe` varchar(255) NULL,
  `family_form_citizenship` varchar(255) NULL,
  `family_form_religion` varchar(255) NULL,
  `family_form_marital_status` varchar(255) NULL,
  `family_form_gender` varchar(255) NULL,
  `family_form_address1` varchar(255) NULL,
  `family_form_address2` varchar(255) NULL,
  `family_form_address3` varchar(255) NULL,
  `family_form_postcode` varchar(255) NULL,
  `family_form_city` varchar(255) NULL,
  `family_form_state` varchar(255) NULL,
  `family_form_contact_no` varchar(255) NULL,
  `family_form_race` varchar(255) NULL,
  `family_form_place_of_birth` varchar(255) NULL,
  `family_form_emp_status` varchar(255) NULL,
  `family_form_emp_name` varchar(255) NULL,
  `family_form_emp_address` varchar(255) NULL,
  `family_form_doc_path_email` varchar(255) NULL,
  `family_form_doc_image_no` varchar(255) NULL,
  `worker_key` integer(11) NULL,
  `fmDoc1_type_of_documents` text,
  `fmDoc1_document_id` varchar(20) DEFAULT NULL,
  `fmDoc1_place_of_issue` varchar(20) DEFAULT NULL,
  `fmDoc1_document_issued_date` varchar(20) DEFAULT NULL,
  `fmDoc1_document_expiry_date` varchar(20) DEFAULT NULL,
  `fmDoc1_issuing_country` varchar(100) DEFAULT NULL,
  `fmDoc1_document_status` varchar(50) DEFAULT NULL,
  `fmDoc1_status_of_current_document` varchar(50) DEFAULT NULL,
  `fmDoc2_type_of_documents` text,
  `fmDoc2_document_id` varchar(20) DEFAULT NULL,
  `fmDoc2_place_of_issue` text,
  `fmDoc2_document_issued_date` varchar(20) DEFAULT NULL,
  `fmDoc2_document_expiry_date` varchar(20) DEFAULT NULL,
  `fmDoc2_issuing_country` varchar(150) DEFAULT NULL,
  `fmDoc2_document_status` varchar(50) DEFAULT NULL,
  `fmDoc2_status_of_current_document` varchar(50) DEFAULT NULL
);